# Generated by Django 4.1.7 on 2023-04-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_header',
            field=models.CharField(max_length=120),
        ),
    ]
