# Generated by Django 4.1.7 on 2023-04-15 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_post_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('0', 'статья'), ('1', 'новость')], default='0', max_length=1)),
                ('input_date_time', models.DateTimeField(auto_now_add=True)),
                ('post_header', models.CharField(max_length=120)),
                ('post_body', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author')),
            ],
        ),
    ]
