# Generated by Django 4.1.7 on 2023-04-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_news',
            name='post_type',
            field=models.CharField(choices=[('0', 'статья'), ('1', 'новость')], default='1', max_length=1),
        ),
    ]
