# Generated by Django 4.1.7 on 2023-04-23 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_news',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.category'),
            preserve_default=False,
        ),
    ]
